# Generated by Django 5.1.2 on 2024-10-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_product_product_category_new_delete_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='new_name',
            field=models.CharField(max_length=64),
        ),
    ]
